print ("A: Hola como estas?, Mucho gusto Javier")
print ("B: Bien mcuahs gracias, un gusto mi nombre es Fernando")
print ("A: Como te va en las finanzas? ")
print ("B: Muy bien gracias por preguntar. y a ti?")
print ("A: Bien aunque siento que la situacion del pais esta un poco complicada por los gobiernos entrantes")
print ("B: Si es verdad, la situacion es estable para mi ya que tengo empleo pero esta dificil para los que estan buscando empleo")
print ("A: Yo estoy iniciando un emprendimiento ya que me quede sin empleo pero el gobierno no apoya a los pequeños emprendedores")
print ("B: Todo debe ser constante no te desanimes, sabes que con practica y disciplina en algun momento todo mejora")
print ("A: Muchas gracias por tu consejo")
print ("B: con gusto espero que te vaya muy bien")
print ("A: igual para ti un gusto conocerte, adios")
print ("B: que estes bien y ten un buen dia")