print ("TUTORIAL DE COMO BARRER UNA HABITACION")
print ("1. Levanta toda la ropa, zapatos, juguetes y objetos que se encuentren en el piso de la habitacion")
print ("2. Ahora debes ir a la parte mas lejana de la habitacion y tomar la escoba con las dos manos")
print ("3. Al tomar la escoba con las dos manos no debe ser ni muy arriba ni muy abajo, se debe tomar a la altura de tu pecho")
print ("4. Empieza a barrer la habitacion en sentido de la dilatacion o espacio de baldosa o tablado")
print ("5. Evita barrer muy fuerte para no generar polvo y que el mismo quede en el ambeinte de tu habitacion")
print ("6. Barre desde el final y acercandote cada vez mas a la puerta de la habitacion")
print ("7. Mueve sillas, armarios, cama y todo objeto que este dentro de la habitacion para garantizar sacar todo el mugre")
print ("8. Cuando llegues a la puerta de la habitacion debes utilizar un recogedor para asi poner todo lo barrido dentro del recogedor")
print ("9. Lleva el recogedor al shut de basura y deposita alli toda la suciedad que barriste")
print ("10. Disfruta de tu cuarto ordenado :) 👌")
print ("😎")